color_theme = "ecopunk"
theme_background = True
truecolor = True
graph_symbol = "braille"
shown_boxes = "cpu mem net proc"
update_ms = 1500
proc_sorting = "cpu lazy"
proc_colors = True
proc_gradient = True
cpu_graph_upper = "total"
cpu_graph_lower = "user"
mem_graphs = True
show_swap = True
net_auto = True
net_sync = True
show_battery = True
